from pathlib import Path

from app.config.settings import Settings
from app.database.models import SecuritySummary, TokenSnapshot
from app.analyzers.token_score import score_token


def _settings() -> Settings:
    return Settings(
        app_version="v1.5.1",
        telegram_bot_token=None,
        telegram_chat_id=None,
        dexscreener_base_url="https://api.dexscreener.com",
        geckoterminal_base_url="https://api.geckoterminal.com/api/v2",
        goplus_base_url="https://api.gopluslabs.io/api/v1",
        min_liquidity_usd=10000,
        min_volume_5m_usd=5000,
        min_volume_1h_usd=15000,
        alert_score_threshold=65,
        critical_risk_alerts=True,
        poll_interval_seconds=60,
        max_alerts_per_run=10,
        dedup_window_minutes=60,
        max_snapshots_per_run=80,
        max_security_checks_per_run=25,
        min_estimated_gain_pct=500,
        min_estimate_confidence=45,
        alert_critical_risks_without_gain=False,
        memecoin_max_alerts_per_24h=5,
        stock_max_alerts_per_24h=5,
        memecoin_max_alerts_per_run=2,
        stock_max_alerts_per_run=2,
        alert_cap_window_hours=24,
        enable_stock_alerts=True,
        enable_stock_telegram=True,
        stock_symbols=["aapl", "msft"],
        min_stock_estimated_gain_pct=8,
        min_stock_estimate_confidence=55,
        enable_telegram_assistant=True,
        telegram_assistant_max_updates=10,
        enable_advanced_market_intel=True,
        enable_news_intel=True,
        enable_pro_intelligence=True,
        enable_sec_filings_intel=True,
        max_chart_analyses_per_run=6,
        max_news_per_symbol=5,
        max_sec_filings_per_run=6,
        max_sec_filings_per_symbol=5,
        sec_recent_days=14,
        sec_user_agent="TradingAlertAI tests",
        enable_obsidian_memory=False,
        obsidian_vault_path=Path("obsidian/tradingbot v.1"),
        enable_learning_engine=True,
        learning_min_alert_age_minutes=60,
        learning_max_alerts_per_run=300,
        enable_paper_trading=True,
        paper_trade_max_active=20,
        readiness_min_score=75,
        readiness_min_confidence=65,
        outcome_win_return_memecoin_pct=100,
        outcome_win_return_stock_pct=5,
        outcome_loss_return_memecoin_pct=-40,
        outcome_loss_return_stock_pct=-3,
        chains_to_monitor=["ethereum", "base", "bsc", "solana"],
        sqlite_path=Path(":memory:"),
        request_timeout_seconds=15,
        enable_price_snapshots=True,
        snapshot_retention_days=30,
        horizon_min_snapshots=2,
        enable_horizon_evaluator=True,
        backtest_min_samples=5,
        backtest_default_horizon_hours=24,
        enable_weekly_obsidian_report=False,
        enable_atr_based_sltp=True,
        atr_stop_multiplier=2.0,
        atr_tp1_multiplier=2.0,
        atr_tp2_multiplier=4.0,
        enable_trailing_stop=True,
        trailing_activation_pct_stock=5.0,
        trailing_activation_pct_memecoin=50.0,
        trailing_distance_pct_stock=3.0,
        trailing_distance_pct_memecoin=25.0,
        enable_learned_weights=False,
        learned_weights_min_samples=5,
        learned_weights_min_confidence=40,
        learned_weights_per_feature_max=3.0,
        learned_weights_max_adjustment=10.0,
        enable_learning_gate=False,
        learning_gate_min_win_rate=0.45,
        learning_gate_min_samples=10,
        learning_gate_horizon_hours=24,
        learning_gate_since_days=30,
        enable_forex_collector=False,
        forex_symbols=["eurusd=x", "gc=f"],
        account_starting_balance=10000.0,
        max_open_trades_total=5,
        max_open_trades_stock=3,
        max_open_trades_forex=4,
        max_open_trades_gold=2,
        risk_per_trade_pct=1.0,
        max_total_risk_pct=6.0,
        max_daily_drawdown_pct=3.0,
        kill_switch_cooldown_hours=24,
        enable_kill_switch_auto=True,
        enable_strategy_router=True,
        strategy_min_confidence=60,
        enable_strategy_breakout=True,
        enable_strategy_mean_reversion=True,
        enable_strategy_momentum=True,
        enable_strategy_news_catalyst=True,
        enable_partial_close_at_tp1=True,
        partial_close_fraction=0.5,
        enable_time_based_exit=True,
        default_time_horizon_hours=48,
        enable_invalidation_exit=True,
        lifecycle_reeval_every_n_cycles=5,
        enable_memecoin_telegram=False,
        enable_memecoin_engine=True,
        enable_mt5_reader=False,
        mt5_path=None,
        mt5_login=None,
        mt5_password=None,
        mt5_server=None,
        mt5_connection_timeout_ms=5000,
        mt5_server_tz="",
        paper_price_from_mt5=False,
        enable_macro_context=True,
        enable_trade_action_reports=True,
        enable_macro_collector=False,
        macro_collector_interval_minutes=60,
        enable_cot_collector=False,
        cot_collector_interval_minutes=720,
        enable_economic_calendar=False,
        calendar_buffer_minutes=30,
        calendar_refresh_hours=12,
        enable_strategy_forex_session_breakout=True,
        enable_forex_alerts=False,
        enable_gold_alerts=False,
        max_forex_alerts_per_24h=3,
        max_gold_alerts_per_24h=2,
        max_forex_alerts_per_run=1,
        max_gold_alerts_per_run=1,
        anthropic_api_key=None,
        enable_claude_integration=False,
        claude_model="claude-haiku-4-5",
        claude_max_tokens=1024,
        claude_calls_per_cycle_cap=6,
        claude_cache_ttl_seconds=3600,
        claude_max_cost_per_day_usd=2.0,
        enable_ollama_integration=False,
        ollama_model="llama3.1",
        ollama_base_url="http://localhost:11434",
        ollama_timeout_seconds=30,
        ollama_calls_per_cycle_cap=6,
        enable_llm_advisor=False,
        enable_llm_ensemble=False,
        ollama_second_model="mistral",
        enable_daily_summary=False,
        daily_summary_hour_utc=21,
        enable_continuous_learner=False,
        store_trade_lessons=True,
        performance_baseline_date="2026-06-03",
        enable_exit_shadow=False,
        enable_calendar_gate=False,
        enable_usd_exposure_cap=False,
        max_net_usd_exposure=3,
        enable_regime_gate=False,
        enable_vwap_gate=False,
        vwap_gate_min_dist_pct=0.5,
        enable_ai_agent=False,
        ai_agent_risk_pct=0.5,
        ai_agent_max_open=3,
        ai_agent_max_trades_per_day=6,
        ai_agent_daily_stop_r=3.0,
        ai_agent_min_edge_r=0.05,
        ai_agent_prior_var=0.25,
        ai_agent_noise_var=1.0,
        ai_agent_seed=20261005,
        ai_agent_version=1,
        ai_agent_explore_pct=0.0,
        ai_agent_explore_risk_pct=0.10,
        ai_agent_explore_max_per_day=3,
        ai_agent_explore_daily_stop_r=2.0,
        mt5_broker_profile="icmarkets",
        enable_walk_forward_backtest=True,
        walk_forward_train_days=14,
        walk_forward_test_days=7,
        walk_forward_slide_days=1,
        walk_forward_min_train_samples=10,
        enable_data_quality_monitor=True,
        data_quality_check_every_n_cycles=10,
        data_quality_staleness_max_minutes=15,
        data_quality_gap_threshold_multiplier=2.0,
        enable_csv_export=True,
        csv_export_path="exports",
        enable_early_memecoin_detection=True,
        max_early_pool_age_hours=6,
        enable_memecoin_hunter=True,
        memecoin_hunter_min_volume_velocity_ratio=2.0,
        max_early_memecoin_alerts_per_24h=3,
        max_mature_memecoin_alerts_per_24h=2,
        max_early_memecoin_alerts_per_run=1,
        force_learning_gate_for_memecoin=True,
        bot_mode="trader",
        enable_mt5_demo_trading=False,
        demo_order_require_confirmation=True,
        demo_max_open_trades=1,
        demo_risk_per_trade_pct=0.25,
        demo_max_lot=0.01,
        demo_allowed_symbols=["eurusd", "xauusd"],
        demo_trade_request_ttl_minutes=15,
        enable_real_trading=False,
        enable_auto_confirm_demo=False,
        demo_max_total_risk_pct=10.0,
        enable_scalping_engine=False,
        scalping_allowed_symbols=["EURUSD", "GBPUSD"],
        scalping_risk_per_trade_pct=1.0,
        scalping_max_trades_per_day=30,
        scalping_max_open_trades=3,
        scalping_max_daily_loss_pct=3.0,
        scalping_force_exit_minutes=5,
        scalping_poll_interval_seconds=5,
        scalping_heartbeat_every_n_trades=5,
        scalping_sl_pips=8,
        scalping_tp_pips=12,
        scalping_range_lookback_bars=10,
        enable_scalping_breakout=True,
        enable_scalping_mean_reversion=True,
        scalping_mr_bollinger_period=20,
        scalping_mr_bollinger_std=2.0,
        scalping_mr_rsi_period=14,
        scalping_mr_rsi_overbought=70,
        scalping_mr_rsi_oversold=30,
        strategy_symbol_cooldown_minutes=15,
        enable_strategy_promotion_gate=True,
        strategy_promotion_min_samples=30,
        strategy_promotion_min_expectancy_r=0.0,
        enable_cost_model=True,
        cost_roundtrip_pct_forex=0.02,
        cost_roundtrip_pct_gold=0.03,
        cost_roundtrip_pct_stock=0.05,
        cost_roundtrip_pct_memecoin=0.5,
        enable_realized_learning=False,
        enable_edge_slicing=True,
        edge_slice_min_samples=30,
        enable_sliced_promotion_gate=False,
        enable_ml_predictor=False,
        ml_min_train_samples=100,
        ml_gate_min_samples=400,
        ml_retrain_min_new_trades=20,
        ml_conf_pass=0.65,
        ml_conf_low=0.50,
        # v3.6.0 — Backtest Replay Harness (sync con settings.py)
        enable_backtest_harness=False,
        backtest_timeframe="D1",
        backtest_symbols=[
            "EURUSD",
            "GBPUSD",
            "USDJPY",
            "USDCHF",
            "AUDUSD",
            "USDCAD",
            "NZDUSD",
            "XAUUSD",
        ],
        backtest_cost_multiplier=1.25,
        backtest_stress_cost_multiplier=1.5,
        backtest_sl_slippage_atr=0.05,
        backtest_intrabar_rule="pessimistic",
        backtest_max_configs_per_run=9,
        backtest_wf_train_months=24,
        backtest_wf_test_months=6,
    )


def test_score_marks_critical_security() -> None:
    snapshot = TokenSnapshot(
        chain="ethereum",
        token_address="0xabc",
        symbol="TEST",
        liquidity_usd=50000,
        volume_5m=10000,
        volume_1h=30000,
        is_trending=True,
    )
    security = SecuritySummary(
        honeypot_status="possible_honeypot",
        is_critical=True,
        contract_risk="risky",
    )

    result = score_token(snapshot, security, _settings())

    assert result.critical_risk is True
    assert result.risk_level == "critical"
    assert 0 <= result.score <= 100


def test_score_rewards_liquidity_volume_and_security() -> None:
    snapshot = TokenSnapshot(
        chain="base",
        token_address="0xdef",
        symbol="GOOD",
        liquidity_usd=300000,
        volume_5m=10000,
        volume_1h=40000,
        volume_24h=200000,
        is_trending=True,
        buys_1h=80,
        sells_1h=40,
    )
    security = SecuritySummary(
        honeypot_status="not_detected",
        owner_status="ok",
        mint_risk="ok",
        blacklist_risk="ok",
        contract_risk="ok",
        raw_summary='{"risks":["none_detected"]}',
    )

    result = score_token(snapshot, security, _settings())

    assert result.score >= 80
    assert result.risk_level in {"orange", "red"}
